### ISSUE TITLE
I cannot get "github.com:USGS-EROS/lcmap-change-detection-c.git"

### ISSUE THREAD

**Issue by Chendz321** [USGS-EROS/lcmap-change-detection-c#10]
When I execute the command `$ git clone git@github.com:USGS-EROS/lcmap-change-detection-c.git` in linux, it prints
 `Cloning into 'lcmap-change-detection-c'...
Warning: Permanently added the RSA host key for IP address '192.30.252.123' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
Could you tell me how to due with it ?
Thank you !

**Comment by oubiwann** [comment]
Sure thing!

This sounds like you don't have an SSH key uploaded to Github. You can either add one to your profile or use the HTTPS link for the clone (which Github provides via a drop-down on the project page).

**Comment by Chendz321** [comment]
Thank you very much !
I have got it on your way !
