### ISSUE TITLE
It is not very clear how to get started using CCDC

### ISSUE THREAD

**Issue by kp005** [USGS-EROS/lcmap-change-detection-c#5]
How to get the libraries:

XML2INC
ESPANIC
GSL_SCI_INC
GSL_SCI_LIB
FORTRAN
HDF5INC
HDF5LIB
MATIOLIB

Cannot find most of these except XML2INC.

**Comment by oubiwann** [comment]
I've only built this on Ubuntu, so I can't give any other help that what I've put in the README :-( The packages listed there are for Ubuntu -- you may be able to use those to find out the names of packages on your own system/distro.

Note that the things you've listed above aren't libraries, but rather are variable names in a `Makefile` ... some of which aren't currently used.

**Comment by oubiwann** [comment]
Also, you may have seen these already, but we've got a couple of Docker images in Dockerhub (and thus available for use by the `docker` command line tool) for CCDC:
- https://hub.docker.com/u/usgseros/dashboard/

**Caveat emptor**: the images there are _very_ much under active development :-) We're going to be pushing up changes to the Docker image sometime this week with the latest tweaks ... that's going to be happening on a regular basis as we test the C version of the CCDC model running in Docker containers (in preparation for deployment in a Mesos cluster). That being said, anything you find that is broken inside a Docker container of one of the CCDC images is probably a bug (or missing implementation), so feel free to file tickets (with enough details that we can reproduce the error/problem). Enjoy!

**Comment by kp005** [comment]
Hi Duncan,

Thanks a lot for the response. Even I am using Ubuntu, will try to work out!

Regards,
Krishna

-----Original Message-----

**Comment by oubiwann** [comment]
No problem, Krishna!

A couple of other things I should note:
- The `Dockerfile` for c-ccdc has a testing entry point in it right now -- this is going to be removed/changed.
- It's a little inconvenient that the `Dockerfile` for CCDC is in another repo. That repo is a holder for general `Dockerfile`s we need for several different projects inside LCMAP, but a CCDC `Dockerfile` is a special case, and should probably be brought into this repo.
- Overriding a Docker `ENTRYPOINT` can be a little anti-intuituve. I'll add a `make` target so it's easier to start up a CCDC Docker image in interactive mode.
- None of this stuff is written down yet -- I'll update the README ;-)

Here are the tasks I'll hit to make this easier for you (and these are things we need to do anyway, sooner than later):
- [x] Move C-CCDC `Dockerfile` from lcmap-dockerfiles repo to here
- [x] Add `make` targets for building and publishing image
- [x] Add `make` target for running Docker image in interactive mode (overriding the `ENTRYPOINT` directive)
- [x] Remove Python test entry point and use @CrustyQuarrier's `bash` script CCDC wrapper instead
- [x] Update `README` with helpful info about the above points
  - [x] Create wikipage for developing with/using CCDC docker images
  - [x] Add notes about obtaining CCDC docker images from Dockerhub
  - [x] Add notes about building docker images yourself
  - [x] Add notes about running docker images interactively
- [x] @CrustyQuarrier's added some nice help text to the `bash` script I'll try to make sure that passing `--help` to the docker image will return that and print it to the console; maybe it should go in the README too ...

Note that I'm also going to update the name of this ticket to be a little more general (e.g., about "getting started").

**Comment by oubiwann** [comment]
The python test script has been removed from the `Dockerfile` build and you can now access the `ccdc` binary directly when running the image.

Here's an example of calling `ccdc` inside docker:

```
$ docker run -t usgseros/debian-c-ccdc --help
```

Output:

```
2016:01:03 18:06:13 1:main [ccdc.c]:214 [INFO]:CCDC start_time=Wed Feb  3 18:06:13 2016


Continuous Change Detection and Classification

usage:
ccdc --row=<input row number> --col=<input col number> --inDir=<input directory> --outDir=<output directory> [--sceneList=<file with list of sceneIDs>] [--verbose]

where the following parameters are required:
    --row=: input row number
    --col=: input col number
    --inDir=: input data directory location
    --outDir=: directory location for output files

and the following parameters are optional:
    --sceneList=: file name containing list of sceneIDs (default is all files in inDir)
    -verbose: should intermediate messages be printed? (default is false)

ccdc --help will print the usage statement

Example:
ccdc --row=3845 --col=2918 --inDir=/data/user/in --outDir=/home/user/out --sceneList=/home/user/scene_list.txt --verbose
Note: Previously, the ccdc had to be run from the directory where the input data are located.
      Now, input and output directory locations specifications are required.

2016:01:03 18:06:13 1:main [ccdc.c]:225 [ERROR]:calling get_args
```

**Comment by CrustyQuarrier** [comment]
IS this good or bad?

On Wed, Feb 3, 2016 at 12:10 PM, Duncan McGreggor notifications@github.com
wrote:

> The python test script has been removed from the Dockerfile build and you
> can now access the ccdc binary directly when running the image.
> 
> Here's an example of calling ccdc inside docker:
> 
> $ docker run -t usgseros/debian-c-ccdc --help
> 
> Output:
> 
> 2016:01:03 18:06:13 1:main [ccdc.c]:214 [INFO]:CCDC start_time=Wed Feb  3 18:06:13 2016
> 
> Continuous Change Detection and Classification
> 
> usage:
> ccdc --row=<input row number> --col=<input col number> --inDir=<input directory> --outDir=<output directory> [--sceneList=<file with list of sceneIDs>] [--verbose]
> 
> where the following parameters are required:
>     --row=: input row number
>     --col=: input col number
>     --inDir=: input data directory location
>     --outDir=: directory location for output files
> 
> and the following parameters are optional:
>     --sceneList=: file name containing list of sceneIDs (default is all files in inDir)
>     -verbose: should intermediate messages be printed? (default is false)
> 
> ccdc --help will print the usage statement
> 
> Example:
> ccdc --row=3845 --col=2918 --inDir=/data/user/in --outDir=/home/user/out --sceneList=/home/user/scene_list.txt --verbose
> Note: Previously, the ccdc had to be run from the directory where the input data are located.
>       Now, input and output directory locations specifications are required.
> 
> 2016:01:03 18:06:13 1:main [ccdc.c]:225 [ERROR]:calling get_args
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/USGS-EROS/lcmap-change-detection-c/issues/5#issuecomment-179383552
> .

## 

bdavis
/******************************************************/
Brian Davis
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the U.S. Geological Survey (USGS)
Earth Resources Observation and Science (EROS) Center
47914 252nd Street
Sioux Falls, SD 57198-0001
Phone:  605-594-6856
Fax:      605-594-2828
Cell:      605-321-6355 (cell)
Email:   bdavis@usgs.gov
URL      eros.usgs.gov
Visualize Whirled Peas

**Comment by oubiwann** [comment]
This is great. We can now run CCDC from the command line (as a user) in the same way that it will be run by the distributed execution framework :-)
